apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: mysql-pass
    literals:
        - password=YOUR_PASSWORD
resources:
  - deploy-mysql.yaml
  - deploy-wordpress.yaml
